### ISSUE TITLE
[Bug] CI Tests are failing

### ISSUE THREAD

**Issue by MSNev** [nevware21/ts-utils#306]
The CI tests are failing with an apparent typo -- looks like an updated dependency issue as the same previously checked in code worked and did not have this issue.

07 08 2024 14:22:55.344:ERROR [preprocessor.rollup]: Failed to process ./lib/test/src/common/string/split.test.ts

RollupError: Expected ',', got ':'
    at Object.getRollupError (/home/runner/work/ts-utils/ts-utils/node_modules/rollup/dist/shared/parseAst.js:282:41)
    at ParseError.initialise (/home/runner/work/ts-utils/ts-utils/node_modules/rollup/dist/shared/rollup.js:12934:40)
    at convertNode (/home/runner/work/ts-utils/ts-utils/node_modules/rollup/dist/shared/rollup.js:14630:10)
    at convertProgram (/home/runner/work/ts-utils/ts-utils/node_modules/rollup/dist/shared/rollup.js:13974:12)
    at Module.setSource (/home/runner/work/ts-utils/ts-utils/node_modules/rollup/dist/shared/rollup.js:15788:24)
    at async ModuleLoader.addModuleSource (/home/runner/work/ts-utils/ts-utils/node_modules/rollup/dist/shared/rollup.js:20101:13)

**Comment by nev21** [comment]
After lots of investigation this has been narrowed done to an issue with using chai assertions and karma ONLY running in a Web Worker. I've trialed several options and simply replacing chai (using a local beta of [tripwire](https://github.com/nevware21/tripwire) assertions resolves the issue, as such I've accelerated to conversion of this library into something public and can be published to GitHub).

It's taking longer than expected to make sure that it can be more easily extensible than the original internal version, but planning on releasing an early (incomplete) version shortly to unblock these projects.
